#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 16 12:54:29 2021

@author: harry
"""

import STACK_1
import tkinter as tk
# import NGUI

root = tk.Tk()
root.title("N Body Simulation")
root.geometry('400x300')
app = STACK_1.MyApp(root)
root.mainloop()

print(STACK_1.planets)