#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 16 12:50:59 2021

@author: harry
"""

import tkinter as tk
from tkinter import font
import os


########################################################################
class MyApp(object):
    """"""

    #----------------------------------------------------------------------
    def __init__(self, parent):
        """Constructor"""
        self.root = parent
        self.root.title("Main frame")
        self.frame = tk.Frame(parent)
        self.frame.pack()

        close_btn = tk.Button(self.frame, text="Close Application", command=self.closeApplication)
        close_btn.pack()

        fontStyle = font.Font(family="Lucida Grande", size=25)
        text_intro = "Select Your Planets"
        planetslabel = tk.Label(self.root, text=text_intro, font=fontStyle)
        planetslabel.place(relx=0.25, rely=0.3, anchor="center")

        global lb

        lb = tk.Listbox(self.root, selectmode = "multiple")
        lb.place(relx=0.25, rely=0.5, anchor="center")

        def confirmSelected():
            global planets
            planets = []
            cname = lb.curselection()
            for i in cname:
                op = lb.get(i)
                planets.append(op)
            for val in planets:
                print(val)
            if len(planets) < 2:
                print("At least two planets need to be selected")

        x =["Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto", "AC1", "AC2"]

        for item in range(len(x)):
        	lb.insert(tk.END, x[item])
        	lb.itemconfig(item, bg="#ffffff")


        tk.Button(self.root, text="Confirm Planets", command=confirmSelected).place(relx=0.205, rely=0.62)

        Executefile_btn = tk.Button(self.root, text="Run rando file", command=self.runfile)
        Executefile_btn.place(relx=0.5, rely=0.9)

    #----------------------------------------------------------------------

    def closeApplication(self):
        """"""
        self.root.destroy()

    #----------------------------------------------------------------------

    def runfile(self):
        os.system('python SlimSimulation-K1=K2=0.py')
